[build]
  publish = "public"  # Directory to deploy (containing your site's assets)
  command = ""        # No build command if you're using static HTML/CSS/JS and CDN for DaisyUI

# Optional: If you decide to structure your site as a Single Page Application (SPA) later
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Basic headers for security (optional, but good practice)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.gstatic.com https://*.firebaseio.com; connect-src 'self' wss://*.firebaseio.com https://*.googleapis.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net/npm/daisyui@latest/dist/full.css https://cdn.jsdelivr.net/npm/tailwindcss@latest/dist/tailwind.min.css; img-src 'self' data:; font-src 'self';"
    # Note: Adjust Content-Security-Policy if you use more external resources or inline scripts/styles. Start restrictive and open up as needed.
