name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensure this matches your functions/package.json engine

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase (Service Account)
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY_JSON" > $HOME/firebase-service-account-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-service-account-key.json" >> $GITHUB_ENV

      # New Step: Install function dependencies
      - name: Install Function Dependencies
        run: |
          cd functions 
          npm install

      - name: Deploy to Firebase
        run: firebase deploy --only functions --project tambola-premium --force
        # If you want to be more specific:
        # run: firebase deploy --only hosting,functions --project tambola-premium --force
