name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Write Firebase Service Account Credentials to file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > ${HOME}/firebase-key.json

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project tambola-premium --token "$(cat ${HOME}/firebase-key.json)"
