name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Create this secret in your GitHub repo settings

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensure this matches your functions/package.json engine

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --project tambola-premium --force
        # The command above deploys all configured Firebase features (hosting, functions, rules, etc.)
        # If you want to be more specific, you can use:
        # run: firebase deploy --only hosting,functions --project tambola-premium --force
