name: Deploy to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_firebase:
    name: Deploy Firebase Services
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy to Firebase
        uses: google-github-actions/deploy-firebase@v0.11.0 # Changed from @v0 to a specific version
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          # Optional: specify what to deploy if not everything defined in firebase.json.
          # For example, to deploy only functions and Firestore rules/indexes:
          # args: deploy --only functions,firestore
