name: Deploy to Firebase

on:
  push:
    branches:
      - main # Or your default branch for production deployments
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy_firebase:
    name: Deploy Firebase Services
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }} # e.g., projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }} # e.g., firebase-deploy-sa@your-project-id.iam.gserviceaccount.com

      # Setup Node.js for Firebase CLI (if needed, some deploy actions bundle it)
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18' # Match your Firebase Functions runtime

      # Install Firebase CLI (if not using a pre-packaged deploy action that includes it)
      # - name: Install Firebase CLI
      #   run: npm install -g firebase-tools

      # Deploy to Firebase
      # This action deploys Hosting, Functions, Firestore rules/indexes by default based on firebase.json
      # To deploy only specific services: add ` Largs: '--only functions,firestore'` (for example)
      - name: Deploy to Firebase
        uses: google-github-actions/deploy-firebase@main
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          # Optional: specify what to deploy if not everything defined in firebase.json
          # args: deploy --only functions,firestore
