name: Deploy to Firebase

on:
  push:
    branches:
      - main # Or your default branch if different

jobs:
  deploy_firebase:
    name: Deploy Firebase Functions and Hosting
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Match your functions/package.json engine

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Navigate to functions directory and install dependencies
      - name: Install Functions Dependencies
        run: |
          cd functions
          npm install

      # Authenticate to Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'

      # Deploy to Firebase
      - name: Deploy to Firebase
        run: |
          firebase deploy --only functions,hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --force
